<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Content_Relative</name>
   <tag></tag>
   <elementGuidId>61de552b-97f0-4b0e-92dd-f7e53e661b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.style-scope.ytd-compact-video-renderer > #video-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>video-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-compact-video-renderer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>잔잔한 팝송, 듣기좋은팝송, 부드러운 팝송, Autumn Pop, Popsong 게시자: Eric's Juke Box 1년 전 1시간 41분 조회수 6,338,381회</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>잔잔한 팝송, 듣기좋은팝송, 부드러운 팝송, Autumn Pop, Popsong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            잔잔한 팝송, 듣기좋은팝송, 부드러운 팝송, Autumn Pop, Popsong
          </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-inner&quot;)/div[@id=&quot;related&quot;]/ytd-watch-next-secondary-results-renderer[@class=&quot;style-scope ytd-watch-flexy&quot;]/div[@id=&quot;items&quot;]/ytd-compact-autoplay-renderer[@class=&quot;style-scope ytd-watch-next-secondary-results-renderer&quot;]/div[@id=&quot;contents&quot;]/ytd-compact-video-renderer[@class=&quot;style-scope ytd-compact-autoplay-renderer&quot;]/div[@id=&quot;dismissable&quot;]/div[@class=&quot;details style-scope ytd-compact-video-renderer&quot;]/div[@class=&quot;metadata style-scope ytd-compact-video-renderer&quot;]/a[@class=&quot;yt-simple-endpoint style-scope ytd-compact-video-renderer&quot;]/h3[@class=&quot;style-scope ytd-compact-video-renderer&quot;]/span[@id=&quot;video-title&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='video-title']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dismissable']/div/div/a/h3/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='목록에 추가'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Eric', &quot;'&quot;, 's Juke Box')])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='잔잔한 팝송, 듣기좋은팝송, 부드러운 팝송, Autumn Pop, Popsong']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
   </webElementXpaths>
</WebElementEntity>
